language: node_js
node_js:
  - lts/*
sudo: false
dist: trusty
ci: skip
before_install:
  - npm install -g npm@latest
install:
  - npm install
  - lerna bootstrap

deploy:
- provider: script
  script: lerna publish from-git --yes
  skip_cleanup: true
  on:
    branch: master